kind: MLApp
metadata:
  name: mxnet
spec:
  package_manager: "pip2"
  packages:
    - names:
      {{- range $i, $value := .packages }}
      - "{{ $value }}"
      {{- end }}
      manager: "pip2"
  tasks:
  - name: prepare-data
    resources:
    - name: upload
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 1
      allowFail: true
      images:
        cpu: busybox
      command: "echo \"Uploading Data\";echo \"Done!!!\""
      workdir: "$DATA_DIR"
      volumes:
      - name: data
  - name: train
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: "kuberlab/mlboard-jupyter-mxnetlatest-gpu"
        cpu: "kuberlab/mlboard-jupyter-mxnet"
      command: python
      args: hello.py
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 8Gi
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
      - name: code
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/mlboard-jupyter-mxnet:latest-gpu"
      cpu: "kuberlab/mlboard-jupyter-mxnet:latest"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    volumes:
    - name: lib
      mountPath: /notebooks/lib
    - name: src
      mountPath: /notebooks/src
    - name: training
      mountPath: /notebooks/training
    - name: data
      mountPath: /notebooks/data
    - name: code
      mountPath: /notebooks
  volumes:
  - isLibDir: false
    isTrainLogDir: true
    mountPath: /training
    name: training
    clusterStorage: {{ .storage.value }}
    subPath: training
  - gitRepo:
      repository: {{ .src }}
    isLibDir: false
    isTrainLogDir: false
    mountPath: /src
    name: src
    subPath: "{{ .src_path }}"
  - isLibDir: true
    isTrainLogDir: false
    mountPath: /workspace/lib
    name: lib
    clusterStorage: {{ .storage.value }}
    subPath: lib
  - isLibDir: false
    isTrainLogDir: false
    mountPath: /data
    name: data
    clusterStorage: {{ .storage.value }}
    subPath: {{ .data_path }}
  - isLibDir: false
    isTrainLogDir: false
    mountPath: /code
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
