storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

src: https://github.com/kuberlab-catalog/mxnet

src_path: /mxnet/src

data_path: data

packages:
 - "git+https://github.com/kuberlab/python-mlboardclient.git"
